apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: jenkins
